# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- 
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(4910ed0b-6d83-4182-88a2-6dcbe8d54094)'
    subscriptionId: '4910ed0b-6d83-4182-88a2-6dcbe8d54094'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'PersistRG'
    location: 'East Asia'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)\**\LogicApp.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)\**\LogicApp.parameters.json'
    deploymentMode: 'Incremental'